name: cookbook
channels:
- ioam
- conda-forge
- defaults
dependencies:
- altair=1.2.1=py_0
- bqplot=0.10.1=py36_0
- cartopy=0.15.1=py36_5
- freexl=1.0.4=0
- geos=3.6.2=1
- giflib=5.1.4=0
- hdf4=4.2.13=0
- ipyleaflet=0.5.0=py36_0
- ipyvolume=0.4.0=py36_1
- ipywebrtc=0.3.0=py36_0
- joblib=0.11=py36_0
- json-c=0.12.1=0
- kealib=1.4.7=4
- libdap4=3.19.2=1
- libgpuarray=0.7.5=0
- libiconv=1.15=0
- libnetcdf=4.4.1.1=10
- mako=1.0.7=py36_0
- owslib=0.15.0=py_0
- poppler-data=0.4.8=0
- proj4=4.9.3=5
- pyepsg=0.3.2=py36_0
- pygpu=0.7.5=py36_0
- pymc3=3.2=py36_0
- pyproj=1.9.5.1=py36_0
- pyshp=1.2.12=py_0
- pythreejs=0.4.1=py36_0
- shapely=1.6.2=py36_1
- theano=0.9.0=py36_1
- tqdm=4.19.4=py_0
- traittypes=0.0.6=py36_0
- vega=0.4.4=py36_1
- xerces-c=3.2.0=0
- alabaster=0.7.10=py36h306e16b_0
- anaconda=5.0.1=py36hd30a520_1
- anaconda-client=1.6.5=py36h19c0dcd_0
- anaconda-navigator=1.6.9=py36h11ddaaa_0
- anaconda-project=0.8.0=py36h29abdf5_0
- asn1crypto=0.22.0=py36h265ca7c_1
- astroid=1.5.3=py36hbdb9df2_0
- astropy=2.0.2=py36ha51211e_4
- babel=2.5.0=py36h7d14adf_0
- backports=1.0=py36hfa02d7e_1
- backports.shutil_get_terminal_size=1.0.0=py36hfea85ff_2
- beautifulsoup4=4.6.0=py36h49b8c8c_1
- bitarray=0.8.1=py36h5834eb8_0
- bkcharts=0.2=py36h735825a_0
- blaze=0.11.3=py36h4e06776_0
- bleach=2.0.0=py36h688b259_0
- bokeh=0.12.10=py36hbb0e44a_0
- boto=2.48.0=py36h6e4cd66_1
- bottleneck=1.2.1=py36haac1ea0_0
- bzip2=1.0.6=h0376d23_1
- ca-certificates=2017.08.26=h1d4fec5_0
- cairo=1.14.10=haa5651f_5
- certifi=2017.7.27.1=py36h8b7b77e_0
- cffi=1.10.0=py36had8d393_1
- chardet=3.0.4=py36h0f667ec_1
- click=6.7=py36h5253387_0
- cloudpickle=0.4.0=py36h30f8c20_0
- clyent=1.2.2=py36h7e57e65_1
- colorama=0.3.9=py36h489cec4_0
- contextlib2=0.5.5=py36h6c84a62_0
- cryptography=2.0.3=py36ha225213_1
- cudatoolkit=8.0=3
- curl=7.55.1=hcb0b314_2
- cycler=0.10.0=py36h93f1223_0
- cython=0.26.1=py36h21c49d0_0
- cytoolz=0.8.2=py36h708bfd4_0
- dask=0.15.3=py36hdc2c8aa_0
- dask-core=0.15.3=py36h10e6167_0
- datashape=0.5.4=py36h3ad6b5c_0
- dbus=1.10.22=h3b5a359_0
- decorator=4.1.2=py36hd076ac8_0
- distributed=1.19.1=py36h25f3894_0
- docutils=0.14=py36hb0f60f5_0
- entrypoints=0.2.3=py36h1aec115_2
- et_xmlfile=1.0.1=py36hd6bccc3_0
- expat=2.2.4=hc00ebd1_1
- fastcache=1.0.2=py36h5b0c431_0
- filelock=2.0.12=py36hacfa1f5_0
- flask=0.12.2=py36hb24657c_0
- flask-cors=3.0.3=py36h2d857d3_0
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=h52ed37b_0
- get_terminal_size=1.0.0=haa9412d_0
- gevent=1.2.2=py36h2fe25dc_0
- glib=2.53.6=hc861d11_1
- glob2=0.5=py36h2c1b292_1
- gmp=6.1.2=hb3b607b_0
- gmpy2=2.0.8=py36h55090d7_1
- graphite2=1.3.10=hc526e54_0
- greenlet=0.4.12=py36h2d503a6_0
- gsl=2.2.1=h0c605f7_3
- gst-plugins-base=1.12.2=he3457e5_0
- gstreamer=1.12.2=h4f93127_0
- h5py=2.7.0=py36he81ebca_1
- harfbuzz=1.5.0=h2545bd6_0
- hdf5=1.10.1=hb0523eb_0
- heapdict=1.0.0=py36h79797d7_0
- html5lib=0.999999999=py36h2cfc398_0
- icu=58.2=h211956c_0
- idna=2.6=py36h82fb2a8_1
- imageio=2.2.0=py36he555465_0
- imagesize=0.7.1=py36h52d8127_0
- intel-openmp=2018.0.0=h15fc484_7
- ipykernel=4.6.1=py36hbf841aa_0
- ipyparallel=6.0.2=py36_0
- ipython=6.1.0=py36hc72a948_1
- ipython_genutils=0.2.0=py36hb52b0d5_0
- ipywidgets=7.0.0=py36h7b55c3a_0
- isort=4.2.15=py36had401c0_0
- itsdangerous=0.24=py36h93cc618_1
- jbig=2.1=hdba287a_0
- jdcal=1.3=py36h4c697fb_0
- jedi=0.10.2=py36h552def0_0
- jinja2=2.9.6=py36h489bce4_1
- jpeg=9b=habf39ab_1
- jsonschema=2.6.0=py36h006f8b5_0
- jupyter=1.0.0=py36h9896ce5_0
- jupyter_client=5.1.0=py36h614e9ea_0
- jupyter_console=5.2.0=py36he59e554_1
- jupyter_core=4.3.0=py36h357a921_0
- jupyterlab=0.27.0=py36h86377d0_2
- jupyterlab_launcher=0.4.0=py36h4d8058d_0
- krb5=1.14.2=h56d4222_4
- lazy-object-proxy=1.3.1=py36h10fcdad_0
- libboost=1.65.1=h4055789_3
- libedit=3.1=heed3624_0
- libffi=3.2.1=h4deb6c0_3
- libgcc-ng=7.2.0=h7cc24e2_2
- libgdal=2.0.0=1
- libgfortran-ng=7.2.0=h9f7466a_2
- libkml=1.3.0=h8777076_2
- libpng=1.6.32=hda9c8bc_2
- libpq=9.5.4=0
- libsodium=1.0.13=h31c71d8_2
- libspatialite=4.3.0a=h72746d6_18
- libssh2=1.8.0=h8c220ad_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- libtiff=4.0.8=h90200ff_9
- libtool=2.4.6=hd50d1a6_0
- libxcb=1.12=h84ff03f_3
- libxml2=2.9.4=h6b072ca_5
- libxslt=1.1.29=hcf9102b_5
- line_profiler=2.0=py36_0
- llvmlite=0.20.0=py36_0
- locket=0.2.0=py36h787c0ad_1
- lxml=4.1.0=py36h5b66e50_0
- lzo=2.10=h1bfc0ba_1
- markupsafe=1.0=py36hd9260cd_1
- matplotlib=2.1.0=py36hba5de38_0
- mccabe=0.6.1=py36h5ad9710_1
- memory_profiler=0.47=py36hfa32046_0
- mistune=0.7.4=py36hbab8784_0
- mkl=2018.0.0=hb491cac_4
- mkl-service=1.1.2=py36h17a0993_4
- mpc=1.0.3=hf803216_4
- mpfr=3.1.5=h12ff648_1
- mpmath=0.19=py36h8cc018b_2
- msgpack-python=0.4.8=py36hec4c5d1_0
- multipledispatch=0.4.9=py36h41da3fb_0
- navigator-updater=0.1.0=py36h14770f7_0
- nbconvert=5.3.1=py36hb41ffb7_0
- nbformat=4.4.0=py36h31c9010_0
- ncurses=6.0=h06874d7_1
- networkx=2.0=py36h7e96fb8_0
- nltk=3.2.4=py36h1a0979f_0
- nose=1.3.7=py36hcdf7029_2
- notebook=5.0.0=py36h0b20546_2
- numba=0.35.0=np113py36_10
- numexpr=2.6.2=py36hdd3393f_1
- numpy=1.13.3=py36ha12f23b_0
- numpydoc=0.7.0=py36h18f165f_0
- odo=0.5.1=py36h90ed295_0
- olefile=0.44=py36h79f9f78_0
- openjpeg=2.2.0=h622c3cc_2
- openpyxl=2.4.8=py36h41dd2a8_1
- openssl=1.0.2l=h077ae2c_5
- packaging=16.8=py36ha668100_1
- pandas=0.20.3=py36h842e28d_2
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py36ha6701b7_1
- pango=1.40.11=h8191d47_0
- partd=0.3.8=py36h36fd896_0
- patchelf=0.9=hf79760b_2
- path.py=10.3.1=py36he0c6f6d_0
- pathlib2=2.3.0=py36h49efa8e_0
- patsy=0.4.1=py36ha3be15e_0
- pcre=8.41=hc71a17e_0
- pep8=1.7.0=py36h26ade29_0
- pexpect=4.2.1=py36h3b9d41b_0
- pickleshare=0.7.4=py36h63277f8_0
- pillow=4.2.1=py36h9119f52_0
- pip=9.0.1=py36h8ec8b28_3
- pixman=0.34.0=h83dc358_2
- pkginfo=1.4.1=py36h215d178_1
- ply=3.10=py36hed35086_0
- poppler=0.60.1=hc909a00_0
- prompt_toolkit=1.0.15=py36h17d85b1_0
- psutil=5.4.0=py36h84c53db_0
- ptyprocess=0.5.2=py36h69acd42_0
- py=1.4.34=py36h0712aa3_1
- pycodestyle=2.3.1=py36hf609f19_0
- pycosat=0.6.2=py36h1a0ea17_1
- pycparser=2.18=py36hf9f622e_1
- pycrypto=2.6.1=py36h6998063_1
- pycurl=7.43.0=py36h5e72054_3
- pyflakes=1.6.0=py36h7bd6a15_0
- pygments=2.2.0=py36h0d3125c_0
- pylint=1.7.4=py36hb9d4533_0
- pyodbc=4.0.17=py36h999153c_0
- pyopenssl=17.2.0=py36h5cc804b_0
- pyparsing=2.2.0=py36hee85983_1
- pyqt=5.6.0=py36h0386399_5
- pysocks=1.6.7=py36hd97a5b1_1
- pytables=3.4.2=py36h3b5282a_2
- pytest=3.2.1=py36h11ad3bb_1
- python=3.6.3=hc9025b9_1
- python-dateutil=2.6.1=py36h88d3b88_1
- pytz=2017.2=py36hc2ccc2a_1
- pywavelets=0.5.2=py36he602eb0_0
- pyyaml=3.12=py36hafb9ca4_1
- pyzmq=16.0.2=py36h3b0cf96_2
- qt=5.6.2=h974d657_12
- qtawesome=0.4.4=py36h609ed8c_0
- qtconsole=4.3.1=py36h8f73b5b_0
- qtpy=1.3.1=py36h3691cc8_0
- r-assertthat=0.2.0=r342h06193eb_0
- r-base=3.4.2=haf99962_0
- r-bh=1.65.0_1=r342h2d7c2ce_0
- r-bindr=0.1=r342hdee8079_0
- r-bindrcpp=0.2=r342h4ea5b31_0
- r-bit=1.1_12=r342h7a05cba_0
- r-bit64=0.9_7=r342hcc44603_0
- r-blob=1.1.0=r342hf606c5c_0
- r-dbi=0.7=r342h835dbd3_0
- r-dbplyr=1.1.0=r342h3750f00_0
- r-digest=0.6.12=r342hee14287_0
- r-dplyr=0.7.4=r342hee63e26_0
- r-glue=1.1.1=r342h3154e12_0
- r-magrittr=1.5=r342h895a831_4
- r-memoise=1.1.0=r342hcbc733d_0
- r-pkgconfig=2.0.1=r342h5d9b92e_0
- r-plogr=0.1_1=r342h6d7f4c2_0
- r-purrr=0.2.3=r342h7916a1c_0
- r-r6=2.2.2=r342hcc750b5_0
- r-rcpp=0.12.13=r342h9f83869_0
- r-rlang=0.1.2=r342hc878738_0
- r-rsqlite=2.0=r342h51f80d0_0
- r-tibble=1.3.4=r342h041fa31_0
- readline=7.0=hac23ff0_3
- requests=2.18.4=py36he2e5f8d_1
- rope=0.10.5=py36h1f8c17e_0
- rpy2=2.9.0=py36r342h348380c_0
- ruamel_yaml=0.11.14=py36ha2fb22d_2
- scikit-image=0.13.0=py36had3c07a_1
- scikit-learn=0.19.1=py36h7aa7ec6_0
- scipy=0.19.1=py36h9976243_3
- seaborn=0.8.0=py36h197244f_0
- setuptools=36.5.0=py36he42e2e1_0
- simplegeneric=0.8.1=py36h2cb9092_0
- singledispatch=3.4.0.3=py36h7a266c3_0
- sip=4.18.1=py36h51ed4ed_2
- six=1.11.0=py36h372c433_1
- snowballstemmer=1.2.1=py36h6febd40_0
- sortedcollections=0.5.3=py36h3c761f9_0
- sortedcontainers=1.5.7=py36hdf89491_0
- sphinx=1.6.3=py36he5f0bdb_0
- sphinxcontrib=1.0=py36h6d0f590_1
- sphinxcontrib-websupport=1.0.1=py36hb5cb234_1
- spyder=3.2.4=py36hbe6152b_0
- sqlalchemy=1.1.13=py36hfb5efd7_0
- sqlite=3.20.1=h6d8b0f3_1
- statsmodels=0.8.0=py36h8533d0b_0
- sympy=1.1.1=py36hc6d1c1c_0
- tblib=1.3.2=py36h34cf8b6_0
- terminado=0.6=py36ha25a19f_0
- testpath=0.3.1=py36h8cadb63_0
- tk=8.6.7=h5979e9b_1
- toolz=0.8.2=py36h81f2dff_0
- tornado=4.5.2=py36h1283b2a_0
- traitlets=4.3.2=py36h674d592_0
- typing=3.6.2=py36h7da032a_0
- unicodecsv=0.14.1=py36ha668878_0
- unixodbc=2.3.4=hc36303a_1
- urllib3=1.22=py36hbe7ace6_0
- util-linux=2.21=0
- wcwidth=0.1.7=py36hdf4376a_0
- webencodings=0.5.1=py36h800622e_1
- werkzeug=0.12.2=py36hc703753_0
- wheel=0.29.0=py36he7f4e38_1
- widgetsnbextension=3.0.2=py36hd01bb71_1
- wrapt=1.10.11=py36h28b7045_0
- xlrd=1.1.0=py36h1db9f0c_1
- xlsxwriter=1.0.2=py36h3de1aca_0
- xlwt=1.3.0=py36h7b00a1f_0
- xz=5.2.3=h2bcbf08_1
- yaml=0.1.7=h96e3832_1
- zeromq=4.2.2=hb0b69da_1
- zict=0.1.3=py36h3a3bf81_0
- zlib=1.2.11=hfbfcf68_1
- holoviews=1.9.0=py36h01658e4_0
- param=1.5.1=py36_0
- pip:
  - autopep8==1.3.3
  - backports.shutil-get-terminal-size==1.0.0
  - bash-kernel==0.7.1
  - coverage==4.4.2
  - cssselect==1.0.1
  - et-xmlfile==1.0.1
  - flake8==3.5.0
  - ipython-genutils==0.2.0
  - ipythonblocks==1.7.1
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - jupyterlab-launcher==0.4.0
  - line-profiler==2.0
  - memory-profiler==0.47
  - prompt-toolkit==1.0.15
  - pydub==0.20.0
  - pypandoc==1.4
  - pytest-cov==2.5.1
  - ruamel-yaml==0.11.14
  - smopy==0.0.6
  - tables==3.4.2
